// ==========================================================================
// Presets.kt -- Named Preset Configurations
// Ported from presets.rs -- keep shared parameters aligned with src/presets.rs
//
// Presets snap all signal-processing parameters to known-good values.
// Think of these like synth patches -- each one is tuned for a specific
// use case. Users pick a preset as a starting point, then tweak.
// ==========================================================================

package com.ashairfoil.chloevibes.audio

// ---------------------------------------------------------------------------
// Preset data class
// ---------------------------------------------------------------------------

/**
 * A complete snapshot of all signal-processing settings.
 * Does NOT include connection/device settings -- only the "patch."
 */
data class Preset(
    val name: String,
    val description: String,
    val category: PresetCategory,

    // Volume / Input
    val mainVolume: Float,

    // Frequency
    val frequencyMode: FrequencyMode,
    val targetFrequency: Float,

    // Gate
    val gateThreshold: Float,
    val autoGateAmount: Float,
    val gateSmoothing: Float,
    /** Soft-knee width; Bass Drum default 0.15 (parity with Rust). */
    val thresholdKnee: Float = 0.15f,

    // Trigger
    val triggerMode: TriggerMode,
    val binaryLevel: Float,
    val hybridBlend: Float,
    /** Dynamic trigger curve; Bass Drum default 1.2 (parity with Rust). */
    val dynamicCurve: Float = 1.2f,

    // ADSR Envelope
    val attackMs: Float,
    val decayMs: Float,
    val sustainLevel: Float,
    val releaseMs: Float,
    val attackCurve: Float,
    val decayCurve: Float,
    val releaseCurve: Float,

    // Output Range
    val minVibe: Float,
    val maxVibe: Float,
    /** Output slew fall time (ms). Boom path ~42 ms for deep troughs. */
    val outputSlewMs: Float = 42f,

    // Climax Engine (defaults = off with neutral settings)
    val climaxEnabled: Boolean = false,
    val climaxIntensity: Float = 0.7f,
    val climaxBuildUpMs: Float = 90_000f,
    val climaxTeaseRatio: Float = 0.18f,
    val climaxTeaseDrop: Float = 0.35f,
    val climaxSurgeBoost: Float = 0.5f,
    val climaxPulseDepth: Float = 0.18f,
    val climaxPattern: ClimaxPattern = ClimaxPattern.Wave
)

// ---------------------------------------------------------------------------
// Preset categories
// ---------------------------------------------------------------------------

enum class PresetCategory(val label: String) {
    /** Starting points / neutral */
    Init("INIT"),
    /** Tracks beats/drums -- short, punchy envelopes */
    Percussion("DRUMS"),
    /** Follows melody/vocals -- smooth, sustained */
    Musical("MUSICAL"),
    /** Bass-focused -- heavy, slow */
    Bass("BASS"),
    /** Special effects and creative use cases */
    Effect("FX");

    companion object {
        fun all(): List<PresetCategory> = listOf(Init, Percussion, Musical, Bass, Effect)
    }
}

// ---------------------------------------------------------------------------
// Factory Presets -- all 29 from the Rust version
// ---------------------------------------------------------------------------

fun factoryPresets(): List<Preset> = listOf(
    // === INIT ===
    // Flagship: bass-drum BOOM — instant peak, long natural decay, near-zero floor.
    Preset(
        name = "Bass Drum",
        description = "Maximum natural BOOM — kick-only, instant hit, long musical decay into silence",
        category = PresetCategory.Init,
        mainVolume = 1.90f,
        frequencyMode = FrequencyMode.LowPass,
        targetFrequency = 120f,
        gateThreshold = 0.14f,
        autoGateAmount = 0f,
        gateSmoothing = 0.06f,
        thresholdKnee = 0.15f,
        triggerMode = TriggerMode.Hybrid,
        binaryLevel = 0.82f,
        hybridBlend = 0.58f,
        dynamicCurve = 1.2f,
        attackMs = 20f,
        decayMs = 375f,
        sustainLevel = 0.08f,
        releaseMs = 240f,
        attackCurve = 0.7f,
        decayCurve = 1.8f,
        releaseCurve = 1.3f,
        minVibe = 0f,
        maxVibe = 1f
    ),
    Preset(
        name = "Ride Intensity",
        description = "Pad / continuous follower — smooth loudness ride (not the boom path)",
        category = PresetCategory.Init,
        mainVolume = 1.15f,
        frequencyMode = FrequencyMode.Full,
        targetFrequency = 200f,
        gateThreshold = 0.07f,
        autoGateAmount = 0f,
        gateSmoothing = 0.22f,
        triggerMode = TriggerMode.Dynamic,
        binaryLevel = 0.8f,
        hybridBlend = 0.5f,
        attackMs = 30f,
        decayMs = 160f,
        sustainLevel = 0.9f,
        releaseMs = 320f,
        attackCurve = 1f,
        decayCurve = 1f,
        releaseCurve = 1.15f,
        minVibe = 0f,
        maxVibe = 1f
    ),
    Preset(
        name = "Transparent",
        description = "Minimal processing -- raw audio level drives output",
        category = PresetCategory.Init,
        mainVolume = 1.5f,
        frequencyMode = FrequencyMode.Full,
        targetFrequency = 200f,
        gateThreshold = 0.05f,
        autoGateAmount = 0f,
        gateSmoothing = 0f,
        triggerMode = TriggerMode.Dynamic,
        binaryLevel = 0.8f,
        hybridBlend = 0.5f,
        attackMs = 1f,
        decayMs = 10f,
        sustainLevel = 0.9f,
        releaseMs = 50f,
        attackCurve = 1f,
        decayCurve = 1f,
        releaseCurve = 1f,
        minVibe = 0f,
        maxVibe = 1f
    ),
    // === PERCUSSION ===
    Preset(
        name = "Drum Hit",
        description = "Faster boom (~140 BPM) — full punch, musical decay, deep trough",
        category = PresetCategory.Percussion,
        mainVolume = 1.95f,
        frequencyMode = FrequencyMode.LowPass,
        targetFrequency = 120f,
        gateThreshold = 0.16f,
        autoGateAmount = 0f,
        gateSmoothing = 0.04f,
        thresholdKnee = 0.15f,
        triggerMode = TriggerMode.Hybrid,
        binaryLevel = 0.88f,
        hybridBlend = 0.62f,
        dynamicCurve = 1.2f,
        attackMs = 20f,
        decayMs = 335f,
        sustainLevel = 0.08f,
        releaseMs = 210f,
        attackCurve = 0.7f,
        decayCurve = 1.85f,
        releaseCurve = 1.35f,
        minVibe = 0f,
        maxVibe = 1f
    ),
    Preset(
        name = "Kick Follow",
        description = "Hard binary boom on the kick — pure thump, long fall, silence between",
        category = PresetCategory.Percussion,
        mainVolume = 2.0f,
        frequencyMode = FrequencyMode.LowPass,
        targetFrequency = 100f,
        gateThreshold = 0.18f,
        autoGateAmount = 0f,
        gateSmoothing = 0f,
        thresholdKnee = 0.15f,
        triggerMode = TriggerMode.Hybrid,
        binaryLevel = 0.90f,
        hybridBlend = 0.72f,
        dynamicCurve = 1.2f,
        attackMs = 20f,
        decayMs = 375f,
        sustainLevel = 0.06f,
        releaseMs = 220f,
        attackCurve = 0.7f,
        decayCurve = 1.9f,
        releaseCurve = 1.4f,
        minVibe = 0f,
        maxVibe = 1f
    ),
    Preset(
        name = "Staccato Pulse",
        description = "Sharp on/off -- like a trance gate effect",
        category = PresetCategory.Percussion,
        mainVolume = 1f,
        frequencyMode = FrequencyMode.Full,
        targetFrequency = 200f,
        gateThreshold = 0.18f,
        autoGateAmount = 0f,
        gateSmoothing = 0f,
        triggerMode = TriggerMode.Binary,
        binaryLevel = 1f,
        hybridBlend = 0.5f,
        attackMs = 0.5f,
        decayMs = 5f,
        sustainLevel = 0.95f,
        releaseMs = 30f,
        attackCurve = 0.2f,
        decayCurve = 1f,
        releaseCurve = 3f,
        minVibe = 0f,
        maxVibe = 1f
    ),
    // === MUSICAL ===
    Preset(
        name = "Slow Swell",
        description = "Gradual build like a string section -- long attack, full sustain",
        category = PresetCategory.Musical,
        mainVolume = 1f,
        frequencyMode = FrequencyMode.Full,
        targetFrequency = 200f,
        gateThreshold = 0.10f,
        autoGateAmount = 0f,
        gateSmoothing = 0.3f,
        triggerMode = TriggerMode.Dynamic,
        binaryLevel = 0.8f,
        hybridBlend = 0.5f,
        attackMs = 200f,
        decayMs = 100f,
        sustainLevel = 0.85f,
        releaseMs = 500f,
        attackCurve = 0.7f,
        decayCurve = 1f,
        releaseCurve = 1.5f,
        minVibe = 0.05f,
        maxVibe = 0.85f
    ),
    Preset(
        name = "Vocal Ride",
        description = "Tracks vocal energy -- mid-range focus, smooth dynamics",
        category = PresetCategory.Musical,
        mainVolume = 1.3f,
        frequencyMode = FrequencyMode.BandPass,
        targetFrequency = 1000f,
        gateThreshold = 0.12f,
        autoGateAmount = 0.3f,
        gateSmoothing = 0.2f,
        triggerMode = TriggerMode.Hybrid,
        binaryLevel = 0.5f,
        hybridBlend = 0.3f,
        attackMs = 15f,
        decayMs = 60f,
        sustainLevel = 0.7f,
        releaseMs = 200f,
        attackCurve = 0.5f,
        decayCurve = 1.2f,
        releaseCurve = 1.8f,
        minVibe = 0.05f,
        maxVibe = 0.9f
    ),
    Preset(
        name = "Pluck",
        description = "Quick strike, medium ring-out -- like a guitar pluck",
        category = PresetCategory.Musical,
        mainVolume = 1f,
        frequencyMode = FrequencyMode.Full,
        targetFrequency = 200f,
        gateThreshold = 0.15f,
        autoGateAmount = 0f,
        gateSmoothing = 0f,
        triggerMode = TriggerMode.Dynamic,
        binaryLevel = 0.8f,
        hybridBlend = 0.5f,
        attackMs = 2f,
        decayMs = 120f,
        sustainLevel = 0.3f,
        releaseMs = 300f,
        attackCurve = 0.3f,
        decayCurve = 1.8f,
        releaseCurve = 2.5f,
        minVibe = 0f,
        maxVibe = 1f
    ),
    // === BASS ===
    Preset(
        name = "Sub Throb",
        description = "Deep bass tracking -- heavy, slow, floor-shaking",
        category = PresetCategory.Bass,
        mainVolume = 2f,
        frequencyMode = FrequencyMode.LowPass,
        targetFrequency = 80f,
        gateThreshold = 0.12f,
        autoGateAmount = 0f,
        gateSmoothing = 0.1f,
        triggerMode = TriggerMode.Dynamic,
        binaryLevel = 0.8f,
        hybridBlend = 0.5f,
        attackMs = 8f,
        decayMs = 150f,
        sustainLevel = 0.75f,
        releaseMs = 400f,
        attackCurve = 0.4f,
        decayCurve = 1.2f,
        releaseCurve = 1.5f,
        minVibe = 0.1f,
        maxVibe = 1f
    ),
    Preset(
        name = "Wobble Bass",
        description = "EDM-style -- binary bass pulse with max output",
        category = PresetCategory.Bass,
        mainVolume = 2.5f,
        frequencyMode = FrequencyMode.LowPass,
        targetFrequency = 150f,
        gateThreshold = 0.15f,
        autoGateAmount = 0f,
        gateSmoothing = 0f,
        triggerMode = TriggerMode.Hybrid,
        binaryLevel = 0.85f,
        hybridBlend = 0.6f,
        attackMs = 3f,
        decayMs = 60f,
        sustainLevel = 0.5f,
        releaseMs = 120f,
        attackCurve = 0.3f,
        decayCurve = 1.5f,
        releaseCurve = 2f,
        minVibe = 0f,
        maxVibe = 1f
    ),
    // === EFFECTS ===
    Preset(
        name = "Ambient Wash",
        description = "Always-on gentle hum that swells with the music",
        category = PresetCategory.Effect,
        mainVolume = 0.8f,
        frequencyMode = FrequencyMode.Full,
        targetFrequency = 200f,
        gateThreshold = 0.03f,
        autoGateAmount = 0f,
        gateSmoothing = 0.5f,
        triggerMode = TriggerMode.Dynamic,
        binaryLevel = 0.8f,
        hybridBlend = 0.5f,
        attackMs = 300f,
        decayMs = 200f,
        sustainLevel = 0.9f,
        releaseMs = 1500f,
        attackCurve = 0.6f,
        decayCurve = 1f,
        releaseCurve = 1f,
        minVibe = 0.15f,
        maxVibe = 0.6f
    ),
    Preset(
        name = "Heartbeat",
        description = "Rhythmic pulse -- consistent intensity, dramatic on/off",
        category = PresetCategory.Effect,
        mainVolume = 1f,
        frequencyMode = FrequencyMode.Full,
        targetFrequency = 200f,
        gateThreshold = 0.20f,
        autoGateAmount = 0f,
        gateSmoothing = 0f,
        triggerMode = TriggerMode.Binary,
        binaryLevel = 0.7f,
        hybridBlend = 0.5f,
        attackMs = 10f,
        decayMs = 50f,
        sustainLevel = 0.6f,
        releaseMs = 100f,
        attackCurve = 0.8f,
        decayCurve = 2f,
        releaseCurve = 2.5f,
        minVibe = 0f,
        maxVibe = 0.75f
    ),
    Preset(
        name = "Hi-Hat Tingle",
        description = "High frequency only -- sparkly, delicate, treble-reactive",
        category = PresetCategory.Effect,
        mainVolume = 2f,
        frequencyMode = FrequencyMode.HighPass,
        targetFrequency = 4000f,
        gateThreshold = 0.10f,
        autoGateAmount = 0f,
        gateSmoothing = 0f,
        triggerMode = TriggerMode.Dynamic,
        binaryLevel = 0.8f,
        hybridBlend = 0.5f,
        attackMs = 1f,
        decayMs = 25f,
        sustainLevel = 0.15f,
        releaseMs = 40f,
        attackCurve = 0.2f,
        decayCurve = 2.5f,
        releaseCurve = 3f,
        minVibe = 0f,
        maxVibe = 0.7f
    ),
    // === DOMI 2 OPTIMIZED ===
    Preset(
        name = "Domi Bass Lock",
        description = "Domi 2 bass drum — sub lock, full boom body, deep trough between kicks",
        category = PresetCategory.Bass,
        mainVolume = 1.95f,
        frequencyMode = FrequencyMode.LowPass,
        targetFrequency = 120f,
        gateThreshold = 0.14f,
        autoGateAmount = 0f,
        gateSmoothing = 0.06f,
        thresholdKnee = 0.15f,
        triggerMode = TriggerMode.Hybrid,
        binaryLevel = 0.84f,
        hybridBlend = 0.58f,
        dynamicCurve = 1.2f,
        attackMs = 20f,
        decayMs = 375f,
        sustainLevel = 0.08f,
        releaseMs = 240f,
        attackCurve = 0.7f,
        decayCurve = 1.8f,
        releaseCurve = 1.3f,
        minVibe = 0f,
        maxVibe = 1f
    ),
    Preset(
        name = "Domi Immerse",
        description = "Domi 2 full-range -- smooth dynamic following with generous sustain and body",
        category = PresetCategory.Musical,
        mainVolume = 1.60f,
        frequencyMode = FrequencyMode.Full,
        targetFrequency = 200f,
        gateThreshold = 0.08f,
        autoGateAmount = 0f,
        gateSmoothing = 0.12f,
        triggerMode = TriggerMode.Dynamic,
        binaryLevel = 0.8f,
        hybridBlend = 0.5f,
        attackMs = 12f,
        decayMs = 110f,
        sustainLevel = 0.78f,
        releaseMs = 280f,
        attackCurve = 0.55f,
        decayCurve = 1.2f,
        releaseCurve = 1.4f,
        minVibe = 0.06f,
        maxVibe = 0.92f
    ),
    Preset(
        name = "Domi Edge",
        description = "Domi 2 high-contrast boom — harder gate, lower floor, longer fall into silence",
        category = PresetCategory.Percussion,
        mainVolume = 2.10f,
        frequencyMode = FrequencyMode.LowPass,
        targetFrequency = 110f,
        gateThreshold = 0.18f,
        autoGateAmount = 0f,
        gateSmoothing = 0f,
        thresholdKnee = 0.15f,
        triggerMode = TriggerMode.Hybrid,
        binaryLevel = 0.92f,
        hybridBlend = 0.68f,
        dynamicCurve = 1.2f,
        attackMs = 20f,
        decayMs = 400f,
        sustainLevel = 0.05f,
        releaseMs = 260f,
        attackCurve = 0.7f,
        decayCurve = 1.9f,
        releaseCurve = 1.4f,
        minVibe = 0f,
        maxVibe = 1f
    ),
    // === NEW PRESETS ===
    Preset(
        name = "Deep Trance",
        description = "Hypnotic bass pulse -- slow, deep, relentless build",
        category = PresetCategory.Bass,
        mainVolume = 1.8f,
        frequencyMode = FrequencyMode.LowPass,
        targetFrequency = 100f,
        gateThreshold = 0.10f,
        autoGateAmount = 0f,
        gateSmoothing = 0.15f,
        triggerMode = TriggerMode.Dynamic,
        binaryLevel = 0.8f,
        hybridBlend = 0.5f,
        attackMs = 15f,
        decayMs = 200f,
        sustainLevel = 0.82f,
        releaseMs = 600f,
        attackCurve = 0.5f,
        decayCurve = 0.8f,
        releaseCurve = 1.2f,
        minVibe = 0.12f,
        maxVibe = 1f
    ),
    // Product edge path: climax ON. Stairs escalates; deep tease + true-zero floor.
    Preset(
        name = "Edge & Deny",
        description = "Session arc — stepped build, hard deny to near-silence, aching rebuild; edges without flat-max numbness",
        category = PresetCategory.Effect,
        mainVolume = 1.55f,
        frequencyMode = FrequencyMode.Full,
        targetFrequency = 200f,
        gateThreshold = 0.08f,
        autoGateAmount = 0f,
        gateSmoothing = 0.12f,
        thresholdKnee = 0.15f,
        triggerMode = TriggerMode.Dynamic,
        binaryLevel = 0.78f,
        hybridBlend = 0.45f,
        dynamicCurve = 1.15f,
        attackMs = 22f,
        decayMs = 120f,
        sustainLevel = 0.78f,
        releaseMs = 380f,
        attackCurve = 0.55f,
        decayCurve = 1.05f,
        releaseCurve = 1.35f,
        minVibe = 0f,
        maxVibe = 0.92f,
        outputSlewMs = 42f,
        climaxEnabled = true,
        climaxIntensity = 0.82f,
        climaxBuildUpMs = 100_000f,
        climaxTeaseRatio = 0.28f,
        climaxTeaseDrop = 0.72f,
        climaxSurgeBoost = 0.55f,
        climaxPulseDepth = 0.12f,
        climaxPattern = ClimaxPattern.Stairs
    ),
    Preset(
        name = "Slow Burn",
        description = "Ultra-gradual build -- barely perceptible increase over minutes, then overwhelming",
        category = PresetCategory.Effect,
        mainVolume = 1.2f,
        frequencyMode = FrequencyMode.Full,
        targetFrequency = 200f,
        gateThreshold = 0.06f,
        autoGateAmount = 0f,
        gateSmoothing = 0.25f,
        triggerMode = TriggerMode.Dynamic,
        binaryLevel = 0.8f,
        hybridBlend = 0.5f,
        attackMs = 50f,
        decayMs = 300f,
        sustainLevel = 0.90f,
        releaseMs = 800f,
        attackCurve = 0.4f,
        decayCurve = 0.7f,
        releaseCurve = 1f,
        minVibe = 0.05f,
        maxVibe = 0.80f
    ),
    Preset(
        name = "Rhythm Rider",
        description = "Locks to any beat -- punchy dynamic response with musical sustain tail",
        category = PresetCategory.Percussion,
        mainVolume = 1.4f,
        frequencyMode = FrequencyMode.Full,
        targetFrequency = 200f,
        gateThreshold = 0.15f,
        autoGateAmount = 0.2f,
        gateSmoothing = 0.05f,
        triggerMode = TriggerMode.Hybrid,
        binaryLevel = 0.75f,
        hybridBlend = 0.35f,
        attackMs = 3f,
        decayMs = 80f,
        sustainLevel = 0.55f,
        releaseMs = 180f,
        attackCurve = 0.3f,
        decayCurve = 1.5f,
        releaseCurve = 2f,
        minVibe = 0f,
        maxVibe = 1f
    ),
    // Honest name: climax engine drives the long musical arc.
    Preset(
        name = "Crescendo",
        description = "Climax-driven musical arc — slow Wave build, soft early tease, late surge; contrast floor stays low",
        category = PresetCategory.Musical,
        mainVolume = 1.35f,
        frequencyMode = FrequencyMode.Full,
        targetFrequency = 200f,
        gateThreshold = 0.07f,
        autoGateAmount = 0f,
        gateSmoothing = 0.16f,
        thresholdKnee = 0.15f,
        triggerMode = TriggerMode.Dynamic,
        binaryLevel = 0.8f,
        hybridBlend = 0.5f,
        dynamicCurve = 1.15f,
        attackMs = 28f,
        decayMs = 160f,
        sustainLevel = 0.82f,
        releaseMs = 480f,
        attackCurve = 0.5f,
        decayCurve = 0.9f,
        releaseCurve = 1.25f,
        minVibe = 0.04f,
        maxVibe = 0.94f,
        outputSlewMs = 48f,
        climaxEnabled = true,
        climaxIntensity = 0.78f,
        climaxBuildUpMs = 110_000f,
        climaxTeaseRatio = 0.16f,
        climaxTeaseDrop = 0.42f,
        climaxSurgeBoost = 0.85f,
        climaxPulseDepth = 0.14f,
        climaxPattern = ClimaxPattern.Wave
    ),
    // === MAXIMUM INTENSITY PRESETS ===
    Preset(
        name = "Overwhelm",
        description = "Full-spectrum maximum -- every band drives output, relentless sustained intensity with chaos modulation",
        category = PresetCategory.Effect,
        mainVolume = 2.5f,
        frequencyMode = FrequencyMode.Full,
        targetFrequency = 200f,
        gateThreshold = 0.04f,
        autoGateAmount = 0f,
        gateSmoothing = 0.08f,
        triggerMode = TriggerMode.Hybrid,
        binaryLevel = 0.95f,
        hybridBlend = 0.40f,
        attackMs = 5f,
        decayMs = 40f,
        sustainLevel = 0.95f,
        releaseMs = 150f,
        attackCurve = 0.25f,
        decayCurve = 0.8f,
        releaseCurve = 1.1f,
        minVibe = 0.15f,
        maxVibe = 1f
    ),
    Preset(
        name = "Bass Destroyer",
        description = "Sub-bass locks both motors to the kick -- thundering dual-motor pulses that hit from the inside",
        category = PresetCategory.Bass,
        mainVolume = 2.8f,
        frequencyMode = FrequencyMode.LowPass,
        targetFrequency = 90f,
        gateThreshold = 0.10f,
        autoGateAmount = 0f,
        gateSmoothing = 0.04f,
        triggerMode = TriggerMode.Hybrid,
        binaryLevel = 1f,
        hybridBlend = 0.55f,
        attackMs = 1f,
        decayMs = 45f,
        sustainLevel = 0.70f,
        releaseMs = 100f,
        attackCurve = 0.2f,
        decayCurve = 1.8f,
        releaseCurve = 2.2f,
        minVibe = 0.08f,
        maxVibe = 1f
    ),
    Preset(
        name = "Psy Spiral",
        description = "Trance-optimized -- 126-128 BPM hypnotic build with sub-harmonic resonance and edge-deny cycles",
        category = PresetCategory.Effect,
        mainVolume = 2.0f,
        frequencyMode = FrequencyMode.LowPass,
        targetFrequency = 120f,
        gateThreshold = 0.08f,
        autoGateAmount = 0f,
        gateSmoothing = 0.12f,
        triggerMode = TriggerMode.Dynamic,
        binaryLevel = 0.8f,
        hybridBlend = 0.5f,
        attackMs = 10f,
        decayMs = 180f,
        sustainLevel = 0.88f,
        releaseMs = 500f,
        attackCurve = 0.45f,
        decayCurve = 0.85f,
        releaseCurve = 1.15f,
        minVibe = 0.12f,
        maxVibe = 1f
    ),
    Preset(
        name = "Nerve Storm",
        description = "Maximum chaos -- unpredictable aperiodic modulation with aggressive onset response, impossible to anticipate",
        category = PresetCategory.Effect,
        mainVolume = 2.2f,
        frequencyMode = FrequencyMode.Full,
        targetFrequency = 200f,
        gateThreshold = 0.05f,
        autoGateAmount = 0.15f,
        gateSmoothing = 0.03f,
        triggerMode = TriggerMode.Dynamic,
        binaryLevel = 0.9f,
        hybridBlend = 0.5f,
        attackMs = 2f,
        decayMs = 30f,
        sustainLevel = 0.82f,
        releaseMs = 80f,
        attackCurve = 0.2f,
        decayCurve = 1.4f,
        releaseCurve = 1.8f,
        minVibe = 0.05f,
        maxVibe = 1f
    ),
    Preset(
        name = "Domi Annihilate",
        description = "Domi 2 dual-motor maximum -- both motors independently driven with phase offset, full sub-bass lock",
        category = PresetCategory.Bass,
        mainVolume = 2.6f,
        frequencyMode = FrequencyMode.LowPass,
        targetFrequency = 100f,
        gateThreshold = 0.06f,
        autoGateAmount = 0f,
        gateSmoothing = 0.06f,
        triggerMode = TriggerMode.Hybrid,
        binaryLevel = 0.95f,
        hybridBlend = 0.50f,
        attackMs = 3f,
        decayMs = 50f,
        sustainLevel = 0.90f,
        releaseMs = 120f,
        attackCurve = 0.3f,
        decayCurve = 1.2f,
        releaseCurve = 1.5f,
        minVibe = 0.10f,
        maxVibe = 1f
    ),
    // === EXPERIENCE PRESETS (climax engine enabled — session arc) ===
    // Design rules vs neural adaptation death:
    //   - true-zero / near-zero min_vibe so deny + troughs reset nerves
    //   - moderate sustain (not 0.9+ flat) so music still carves contrast
    //   - pulse_depth ≤ ~0.22 (motor-expressible); deep tease for edge
    //   - Surge presets keep tease_ratio ≤ 0.18 so terminal surge is not cancelled
    Preset(
        name = "Slow Tease",
        description = "Long edging cycle — Stairs climb, deep deny to silence, slow rebuild; stays on the edge without flat-max burn",
        category = PresetCategory.Effect,
        mainVolume = 1.45f,
        frequencyMode = FrequencyMode.Full,
        targetFrequency = 200f,
        gateThreshold = 0.07f,
        autoGateAmount = 0f,
        gateSmoothing = 0.16f,
        thresholdKnee = 0.15f,
        triggerMode = TriggerMode.Dynamic,
        binaryLevel = 0.78f,
        hybridBlend = 0.45f,
        dynamicCurve = 1.15f,
        attackMs = 28f,
        decayMs = 150f,
        sustainLevel = 0.76f,
        releaseMs = 420f,
        attackCurve = 0.5f,
        decayCurve = 0.95f,
        releaseCurve = 1.25f,
        minVibe = 0f,
        maxVibe = 0.90f,
        outputSlewMs = 48f,
        climaxEnabled = true,
        climaxIntensity = 0.78f,
        climaxBuildUpMs = 150_000f,
        climaxTeaseRatio = 0.30f,
        climaxTeaseDrop = 0.75f,
        climaxSurgeBoost = 0.50f,
        climaxPulseDepth = 0.10f,
        climaxPattern = ClimaxPattern.Stairs
    ),
    Preset(
        name = "Ride the Beat",
        description = "Music-locked escalation — hybrid punch + Surge climax; low tease so terminal peaks survive",
        category = PresetCategory.Musical,
        mainVolume = 1.75f,
        frequencyMode = FrequencyMode.Full,
        targetFrequency = 200f,
        gateThreshold = 0.10f,
        autoGateAmount = 0.12f,
        gateSmoothing = 0.07f,
        thresholdKnee = 0.15f,
        triggerMode = TriggerMode.Hybrid,
        binaryLevel = 0.82f,
        hybridBlend = 0.40f,
        dynamicCurve = 1.2f,
        attackMs = 8f,
        decayMs = 95f,
        sustainLevel = 0.62f,
        releaseMs = 210f,
        attackCurve = 0.35f,
        decayCurve = 1.35f,
        releaseCurve = 1.55f,
        minVibe = 0f,
        maxVibe = 1f,
        outputSlewMs = 42f,
        climaxEnabled = true,
        climaxIntensity = 0.74f,
        climaxBuildUpMs = 75_000f,
        climaxTeaseRatio = 0.12f,
        climaxTeaseDrop = 0.38f,
        climaxSurgeBoost = 0.90f,
        climaxPulseDepth = 0.16f,
        climaxPattern = ClimaxPattern.Surge
    ),
    Preset(
        name = "Break Me",
        description = "Hard climax path — fast Surge, deep deny contrast, motor-honest pulse; intensity without constant floor",
        category = PresetCategory.Effect,
        mainVolume = 2.2f,
        frequencyMode = FrequencyMode.Full,
        targetFrequency = 200f,
        gateThreshold = 0.05f,
        autoGateAmount = 0f,
        gateSmoothing = 0.05f,
        thresholdKnee = 0.15f,
        triggerMode = TriggerMode.Hybrid,
        binaryLevel = 0.92f,
        hybridBlend = 0.48f,
        dynamicCurve = 1.25f,
        attackMs = 3f,
        decayMs = 45f,
        sustainLevel = 0.80f,
        releaseMs = 120f,
        attackCurve = 0.28f,
        decayCurve = 1.15f,
        releaseCurve = 1.4f,
        minVibe = 0.02f,
        maxVibe = 1f,
        outputSlewMs = 36f,
        climaxEnabled = true,
        climaxIntensity = 1.0f,
        climaxBuildUpMs = 50_000f,
        climaxTeaseRatio = 0.16f,
        climaxTeaseDrop = 0.58f,
        climaxSurgeBoost = 1.25f,
        climaxPulseDepth = 0.22f,
        climaxPattern = ClimaxPattern.Surge
    ),
    // === BOOM TEMPO MACROS (catalog names match desktop Deep 90 / Club 125 / Hard 140) ===
    // Climax always off — pure bass-drum body. Same recipe as Bass Drum, tempo-scaled.
    Preset(
        name = "Deep 90",
        description = "Deep 90 — slow bass-drum boom, body-long decay into silence",
        category = PresetCategory.Bass,
        mainVolume = 1.85f,
        frequencyMode = FrequencyMode.LowPass,
        targetFrequency = 100f,
        gateThreshold = 0.13f,
        autoGateAmount = 0f,
        gateSmoothing = 0.06f,
        thresholdKnee = 0.15f,
        triggerMode = TriggerMode.Hybrid,
        binaryLevel = 0.80f,
        hybridBlend = 0.55f,
        dynamicCurve = 1.2f,
        attackMs = 20f,
        decayMs = 520f,
        sustainLevel = 0.08f,
        releaseMs = 330f,
        attackCurve = 0.7f,
        decayCurve = 1.8f,
        releaseCurve = 1.3f,
        minVibe = 0f,
        maxVibe = 1f,
        outputSlewMs = 55f
    ),
    Preset(
        name = "Club 125",
        description = "Club 125 — default bass-drum boom (same shape as Bass Drum)",
        category = PresetCategory.Bass,
        mainVolume = 1.90f,
        frequencyMode = FrequencyMode.LowPass,
        targetFrequency = 120f,
        gateThreshold = 0.14f,
        autoGateAmount = 0f,
        gateSmoothing = 0.06f,
        thresholdKnee = 0.15f,
        triggerMode = TriggerMode.Hybrid,
        binaryLevel = 0.82f,
        hybridBlend = 0.58f,
        dynamicCurve = 1.2f,
        attackMs = 20f,
        decayMs = 375f,
        sustainLevel = 0.08f,
        releaseMs = 240f,
        attackCurve = 0.7f,
        decayCurve = 1.8f,
        releaseCurve = 1.3f,
        minVibe = 0f,
        maxVibe = 1f,
        outputSlewMs = 42f
    ),
    Preset(
        name = "Hard 140",
        description = "Hard 140 — harder hit, full musical boom, deep trough",
        category = PresetCategory.Bass,
        mainVolume = 2.15f,
        frequencyMode = FrequencyMode.LowPass,
        targetFrequency = 120f,
        gateThreshold = 0.16f,
        autoGateAmount = 0f,
        gateSmoothing = 0.06f,
        thresholdKnee = 0.15f,
        triggerMode = TriggerMode.Hybrid,
        binaryLevel = 0.90f,
        hybridBlend = 0.68f,
        dynamicCurve = 1.2f,
        attackMs = 20f,
        decayMs = 335f,
        sustainLevel = 0.06f,
        releaseMs = 210f,
        attackCurve = 0.7f,
        decayCurve = 1.9f,
        releaseCurve = 1.3f,
        minVibe = 0f,
        maxVibe = 1f,
        outputSlewMs = 42f
    )
)

/** Get a preset by name (case-insensitive). Migrates legacy Chloe tempo macro names. */
fun findPreset(name: String): Preset? {
    val resolved = when {
        name.equals("Chloe Loose", ignoreCase = true) -> "Deep 90"
        name.equals("Chloe Medium", ignoreCase = true) -> "Club 125"
        name.equals("Chloe Ultimate", ignoreCase = true) -> "Hard 140"
        else -> name
    }
    return factoryPresets().find { it.name.equals(resolved, ignoreCase = true) }
}

/** Get all presets in a given category. */
fun presetsInCategory(category: PresetCategory): List<Preset> =
    factoryPresets().filter { it.category == category }
