// ==========================================================================
// presets.rs — Named Preset Configurations
//
// Presets snap all signal-processing parameters to known-good values.
// Think of these like synth patches — each one is tuned for a specific
// use case. Users pick a preset as a starting point, then tweak.
//
// Naming convention follows synthesizer tradition:
//   - Short evocative name
//   - Description of what it feels like / what it's for
// ==========================================================================

use crate::audio::{ClimaxPattern, FrequencyMode, TriggerMode};

/// A complete snapshot of all signal-processing settings.
/// Does NOT include connection/device settings — only the "patch."
#[derive(Clone, Debug)]
pub struct Preset {
    pub name: &'static str,
    pub description: &'static str,
    pub category: PresetCategory,

    // Volume / Input
    pub main_volume: f32,

    // Frequency
    pub frequency_mode: FrequencyMode,
    pub target_frequency: f32,

    // Gate (Noise Gate)
    pub gate_threshold: f32,
    pub auto_gate_amount: f32,
    pub gate_smoothing: f32,

    // Trigger
    pub trigger_mode: TriggerMode,
    pub binary_level: f32,
    pub hybrid_blend: f32,

    // ADSR Envelope
    pub attack_ms: f32,
    pub decay_ms: f32,
    pub sustain_level: f32,
    pub release_ms: f32,
    pub attack_curve: f32,
    pub decay_curve: f32,
    pub release_curve: f32,

    // Output Range
    pub min_vibe: f32,
    pub max_vibe: f32,

    // Climax Engine (defaults = off with neutral settings)
    pub climax_enabled: bool,
    pub climax_intensity: f32,
    pub climax_build_up_ms: f32,
    pub climax_tease_ratio: f32,
    pub climax_tease_drop: f32,
    pub climax_surge_boost: f32,
    pub climax_pulse_depth: f32,
    pub climax_pattern: ClimaxPattern,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum PresetCategory {
    /// Tracks beats/drums — short, punchy envelopes
    Percussion,
    /// Follows melody/vocals — smooth, sustained
    Musical,
    /// Bass-focused — heavy, slow
    Bass,
    /// Special effects and creative use cases
    Effect,
    /// Starting points / neutral
    Init,
}

impl PresetCategory {
    pub fn label(&self) -> &'static str {
        match self {
            Self::Percussion => "DRUMS",
            Self::Musical => "MUSICAL",
            Self::Bass => "BASS",
            Self::Effect => "FX",
            Self::Init => "INIT",
        }
    }

    pub fn all() -> &'static [PresetCategory] {
        &[
            PresetCategory::Init,
            PresetCategory::Percussion,
            PresetCategory::Musical,
            PresetCategory::Bass,
            PresetCategory::Effect,
        ]
    }
}

// ---------------------------------------------------------------------------
// Factory Presets
// ---------------------------------------------------------------------------

pub fn factory_presets() -> Vec<Preset> {
    vec![
        // === INIT ===
        Preset {
            name: "Ride Intensity",
            description: "Neutral follower - smooth, non-rhythmic response that rides loudness",
            category: PresetCategory::Init,
            main_volume: 1.15,
            frequency_mode: FrequencyMode::Full,
            target_frequency: 200.0,
            gate_threshold: 0.07,
            auto_gate_amount: 0.0,
            gate_smoothing: 0.22,
            trigger_mode: TriggerMode::Dynamic,
            binary_level: 0.8,
            hybrid_blend: 0.5,
            attack_ms: 30.0,
            decay_ms: 160.0,
            sustain_level: 0.9,
            release_ms: 320.0,
            attack_curve: 1.0,
            decay_curve: 1.0,
            release_curve: 1.15,
            min_vibe: 0.0,
            max_vibe: 1.0,
            climax_enabled: false,
            climax_intensity: 0.7,
            climax_build_up_ms: 90_000.0,
            climax_tease_ratio: 0.18,
            climax_tease_drop: 0.35,
            climax_surge_boost: 0.5,
            climax_pulse_depth: 0.18,
            climax_pattern: ClimaxPattern::Wave,
        },
        Preset {
            name: "Transparent",
            description: "Minimal processing — raw audio level drives output",
            category: PresetCategory::Init,
            main_volume: 1.5,
            frequency_mode: FrequencyMode::Full,
            target_frequency: 200.0,
            gate_threshold: 0.05,
            auto_gate_amount: 0.0,
            gate_smoothing: 0.0,
            trigger_mode: TriggerMode::Dynamic,
            binary_level: 0.8,
            hybrid_blend: 0.5,
            attack_ms: 1.0,
            decay_ms: 10.0,
            sustain_level: 0.9,
            release_ms: 50.0,
            attack_curve: 1.0,
            decay_curve: 1.0,
            release_curve: 1.0,
            min_vibe: 0.0,
            max_vibe: 1.0,
            climax_enabled: false,
            climax_intensity: 0.7,
            climax_build_up_ms: 90_000.0,
            climax_tease_ratio: 0.18,
            climax_tease_drop: 0.35,
            climax_surge_boost: 0.5,
            climax_pulse_depth: 0.18,
            climax_pattern: ClimaxPattern::Wave,
        },
        // === PERCUSSION ===
        Preset {
            name: "Drum Hit",
            description: "Tight punch — snappy attack, fast decay, minimal sustain",
            category: PresetCategory::Percussion,
            main_volume: 1.2,
            frequency_mode: FrequencyMode::Full,
            target_frequency: 200.0,
            gate_threshold: 0.20,
            auto_gate_amount: 0.0,
            gate_smoothing: 0.0,
            trigger_mode: TriggerMode::Dynamic,
            binary_level: 0.8,
            hybrid_blend: 0.5,
            attack_ms: 1.0,
            decay_ms: 40.0,
            sustain_level: 0.2,
            release_ms: 60.0,
            attack_curve: 0.3,
            decay_curve: 2.0,
            release_curve: 2.5,
            min_vibe: 0.0,
            max_vibe: 1.0,
            climax_enabled: false,
            climax_intensity: 0.7,
            climax_build_up_ms: 90_000.0,
            climax_tease_ratio: 0.18,
            climax_tease_drop: 0.35,
            climax_surge_boost: 0.5,
            climax_pulse_depth: 0.18,
            climax_pattern: ClimaxPattern::Wave,
        },
        Preset {
            name: "Kick Follow",
            description: "Locks to the kick drum — bass-only, binary pulse",
            category: PresetCategory::Percussion,
            main_volume: 1.5,
            frequency_mode: FrequencyMode::LowPass,
            target_frequency: 120.0,
            gate_threshold: 0.25,
            auto_gate_amount: 0.0,
            gate_smoothing: 0.0,
            trigger_mode: TriggerMode::Binary,
            binary_level: 0.9,
            hybrid_blend: 0.5,
            attack_ms: 2.0,
            decay_ms: 30.0,
            sustain_level: 0.1,
            release_ms: 80.0,
            attack_curve: 0.3,
            decay_curve: 2.5,
            release_curve: 3.0,
            min_vibe: 0.0,
            max_vibe: 1.0,
            climax_enabled: false,
            climax_intensity: 0.7,
            climax_build_up_ms: 90_000.0,
            climax_tease_ratio: 0.18,
            climax_tease_drop: 0.35,
            climax_surge_boost: 0.5,
            climax_pulse_depth: 0.18,
            climax_pattern: ClimaxPattern::Wave,
        },
        Preset {
            name: "Staccato Pulse",
            description: "Sharp on/off — like a trance gate effect",
            category: PresetCategory::Percussion,
            main_volume: 1.0,
            frequency_mode: FrequencyMode::Full,
            target_frequency: 200.0,
            gate_threshold: 0.18,
            auto_gate_amount: 0.0,
            gate_smoothing: 0.0,
            trigger_mode: TriggerMode::Binary,
            binary_level: 1.0,
            hybrid_blend: 0.5,
            attack_ms: 0.5,
            decay_ms: 5.0,
            sustain_level: 0.95,
            release_ms: 30.0,
            attack_curve: 0.2,
            decay_curve: 1.0,
            release_curve: 3.0,
            min_vibe: 0.0,
            max_vibe: 1.0,
            climax_enabled: false,
            climax_intensity: 0.7,
            climax_build_up_ms: 90_000.0,
            climax_tease_ratio: 0.18,
            climax_tease_drop: 0.35,
            climax_surge_boost: 0.5,
            climax_pulse_depth: 0.18,
            climax_pattern: ClimaxPattern::Wave,
        },
        // === MUSICAL ===
        Preset {
            name: "Slow Swell",
            description: "Gradual build like a string section — long attack, full sustain",
            category: PresetCategory::Musical,
            main_volume: 1.0,
            frequency_mode: FrequencyMode::Full,
            target_frequency: 200.0,
            gate_threshold: 0.10,
            auto_gate_amount: 0.0,
            gate_smoothing: 0.3,
            trigger_mode: TriggerMode::Dynamic,
            binary_level: 0.8,
            hybrid_blend: 0.5,
            attack_ms: 200.0,
            decay_ms: 100.0,
            sustain_level: 0.85,
            release_ms: 500.0,
            attack_curve: 0.7,
            decay_curve: 1.0,
            release_curve: 1.5,
            min_vibe: 0.05,
            max_vibe: 0.85,
            climax_enabled: false,
            climax_intensity: 0.7,
            climax_build_up_ms: 90_000.0,
            climax_tease_ratio: 0.18,
            climax_tease_drop: 0.35,
            climax_surge_boost: 0.5,
            climax_pulse_depth: 0.18,
            climax_pattern: ClimaxPattern::Wave,
        },
        Preset {
            name: "Vocal Ride",
            description: "Tracks vocal energy — mid-range focus, smooth dynamics",
            category: PresetCategory::Musical,
            main_volume: 1.3,
            frequency_mode: FrequencyMode::BandPass,
            target_frequency: 1000.0,
            gate_threshold: 0.12,
            auto_gate_amount: 0.3,
            gate_smoothing: 0.2,
            trigger_mode: TriggerMode::Hybrid,
            binary_level: 0.5,
            hybrid_blend: 0.3,
            attack_ms: 15.0,
            decay_ms: 60.0,
            sustain_level: 0.7,
            release_ms: 200.0,
            attack_curve: 0.5,
            decay_curve: 1.2,
            release_curve: 1.8,
            min_vibe: 0.05,
            max_vibe: 0.9,
            climax_enabled: false,
            climax_intensity: 0.7,
            climax_build_up_ms: 90_000.0,
            climax_tease_ratio: 0.18,
            climax_tease_drop: 0.35,
            climax_surge_boost: 0.5,
            climax_pulse_depth: 0.18,
            climax_pattern: ClimaxPattern::Wave,
        },
        Preset {
            name: "Pluck",
            description: "Quick strike, medium ring-out — like a guitar pluck",
            category: PresetCategory::Musical,
            main_volume: 1.0,
            frequency_mode: FrequencyMode::Full,
            target_frequency: 200.0,
            gate_threshold: 0.15,
            auto_gate_amount: 0.0,
            gate_smoothing: 0.0,
            trigger_mode: TriggerMode::Dynamic,
            binary_level: 0.8,
            hybrid_blend: 0.5,
            attack_ms: 2.0,
            decay_ms: 120.0,
            sustain_level: 0.3,
            release_ms: 300.0,
            attack_curve: 0.3,
            decay_curve: 1.8,
            release_curve: 2.5,
            min_vibe: 0.0,
            max_vibe: 1.0,
            climax_enabled: false,
            climax_intensity: 0.7,
            climax_build_up_ms: 90_000.0,
            climax_tease_ratio: 0.18,
            climax_tease_drop: 0.35,
            climax_surge_boost: 0.5,
            climax_pulse_depth: 0.18,
            climax_pattern: ClimaxPattern::Wave,
        },
        // === BASS ===
        Preset {
            name: "Sub Throb",
            description: "Deep bass tracking — heavy, slow, floor-shaking",
            category: PresetCategory::Bass,
            main_volume: 2.0,
            frequency_mode: FrequencyMode::LowPass,
            target_frequency: 80.0,
            gate_threshold: 0.12,
            auto_gate_amount: 0.0,
            gate_smoothing: 0.1,
            trigger_mode: TriggerMode::Dynamic,
            binary_level: 0.8,
            hybrid_blend: 0.5,
            attack_ms: 8.0,
            decay_ms: 150.0,
            sustain_level: 0.75,
            release_ms: 400.0,
            attack_curve: 0.4,
            decay_curve: 1.2,
            release_curve: 1.5,
            min_vibe: 0.1,
            max_vibe: 1.0,
            climax_enabled: false,
            climax_intensity: 0.7,
            climax_build_up_ms: 90_000.0,
            climax_tease_ratio: 0.18,
            climax_tease_drop: 0.35,
            climax_surge_boost: 0.5,
            climax_pulse_depth: 0.18,
            climax_pattern: ClimaxPattern::Wave,
        },
        Preset {
            name: "Wobble Bass",
            description: "EDM-style — binary bass pulse with max output",
            category: PresetCategory::Bass,
            main_volume: 2.5,
            frequency_mode: FrequencyMode::LowPass,
            target_frequency: 150.0,
            gate_threshold: 0.15,
            auto_gate_amount: 0.0,
            gate_smoothing: 0.0,
            trigger_mode: TriggerMode::Hybrid,
            binary_level: 0.85,
            hybrid_blend: 0.6,
            attack_ms: 3.0,
            decay_ms: 60.0,
            sustain_level: 0.5,
            release_ms: 120.0,
            attack_curve: 0.3,
            decay_curve: 1.5,
            release_curve: 2.0,
            min_vibe: 0.0,
            max_vibe: 1.0,
            climax_enabled: false,
            climax_intensity: 0.7,
            climax_build_up_ms: 90_000.0,
            climax_tease_ratio: 0.18,
            climax_tease_drop: 0.35,
            climax_surge_boost: 0.5,
            climax_pulse_depth: 0.18,
            climax_pattern: ClimaxPattern::Wave,
        },
        // === EFFECTS ===
        Preset {
            name: "Ambient Wash",
            description: "Always-on gentle hum that swells with the music",
            category: PresetCategory::Effect,
            main_volume: 0.8,
            frequency_mode: FrequencyMode::Full,
            target_frequency: 200.0,
            gate_threshold: 0.03,
            auto_gate_amount: 0.0,
            gate_smoothing: 0.5,
            trigger_mode: TriggerMode::Dynamic,
            binary_level: 0.8,
            hybrid_blend: 0.5,
            attack_ms: 300.0,
            decay_ms: 200.0,
            sustain_level: 0.9,
            release_ms: 1500.0,
            attack_curve: 0.6,
            decay_curve: 1.0,
            release_curve: 1.0,
            min_vibe: 0.15,
            max_vibe: 0.6,
            climax_enabled: false,
            climax_intensity: 0.7,
            climax_build_up_ms: 90_000.0,
            climax_tease_ratio: 0.18,
            climax_tease_drop: 0.35,
            climax_surge_boost: 0.5,
            climax_pulse_depth: 0.18,
            climax_pattern: ClimaxPattern::Wave,
        },
        Preset {
            name: "Heartbeat",
            description: "Rhythmic pulse — consistent intensity, dramatic on/off",
            category: PresetCategory::Effect,
            main_volume: 1.0,
            frequency_mode: FrequencyMode::Full,
            target_frequency: 200.0,
            gate_threshold: 0.20,
            auto_gate_amount: 0.0,
            gate_smoothing: 0.0,
            trigger_mode: TriggerMode::Binary,
            binary_level: 0.7,
            hybrid_blend: 0.5,
            attack_ms: 10.0,
            decay_ms: 50.0,
            sustain_level: 0.6,
            release_ms: 100.0,
            attack_curve: 0.8,
            decay_curve: 2.0,
            release_curve: 2.5,
            min_vibe: 0.0,
            max_vibe: 0.75,
            climax_enabled: false,
            climax_intensity: 0.7,
            climax_build_up_ms: 90_000.0,
            climax_tease_ratio: 0.18,
            climax_tease_drop: 0.35,
            climax_surge_boost: 0.5,
            climax_pulse_depth: 0.18,
            climax_pattern: ClimaxPattern::Wave,
        },
        Preset {
            name: "Hi-Hat Tingle",
            description: "High frequency only — sparkly, delicate, treble-reactive",
            category: PresetCategory::Effect,
            main_volume: 2.0,
            frequency_mode: FrequencyMode::HighPass,
            target_frequency: 4000.0,
            gate_threshold: 0.10,
            auto_gate_amount: 0.0,
            gate_smoothing: 0.0,
            trigger_mode: TriggerMode::Dynamic,
            binary_level: 0.8,
            hybrid_blend: 0.5,
            attack_ms: 1.0,
            decay_ms: 25.0,
            sustain_level: 0.15,
            release_ms: 40.0,
            attack_curve: 0.2,
            decay_curve: 2.5,
            release_curve: 3.0,
            min_vibe: 0.0,
            max_vibe: 0.7,
            climax_enabled: false,
            climax_intensity: 0.7,
            climax_build_up_ms: 90_000.0,
            climax_tease_ratio: 0.18,
            climax_tease_drop: 0.35,
            climax_surge_boost: 0.5,
            climax_pulse_depth: 0.18,
            climax_pattern: ClimaxPattern::Wave,
        },
        // === DOMI 2 OPTIMIZED ===
        Preset {
            name: "Domi Bass Lock",
            description: "Domi 2 optimized — locks to bass/kick, punchy hybrid pulses with sustain body",
            category: PresetCategory::Bass,
            main_volume: 1.90,
            frequency_mode: FrequencyMode::LowPass,
            target_frequency: 140.0,
            gate_threshold: 0.14,
            auto_gate_amount: 0.0,
            gate_smoothing: 0.06,
            trigger_mode: TriggerMode::Hybrid,
            binary_level: 0.78,
            hybrid_blend: 0.48,
            attack_ms: 2.0,
            decay_ms: 55.0,
            sustain_level: 0.52,
            release_ms: 85.0,
            attack_curve: 0.35,
            decay_curve: 1.6,
            release_curve: 1.9,
            min_vibe: 0.05,
            max_vibe: 1.0,
            climax_enabled: false,
            climax_intensity: 0.7,
            climax_build_up_ms: 90_000.0,
            climax_tease_ratio: 0.18,
            climax_tease_drop: 0.35,
            climax_surge_boost: 0.5,
            climax_pulse_depth: 0.18,
            climax_pattern: ClimaxPattern::Wave,
        },
        Preset {
            name: "Domi Immerse",
            description: "Domi 2 full-range — smooth dynamic following with generous sustain and body",
            category: PresetCategory::Musical,
            main_volume: 1.60,
            frequency_mode: FrequencyMode::Full,
            target_frequency: 200.0,
            gate_threshold: 0.08,
            auto_gate_amount: 0.0,
            gate_smoothing: 0.12,
            trigger_mode: TriggerMode::Dynamic,
            binary_level: 0.8,
            hybrid_blend: 0.5,
            attack_ms: 12.0,
            decay_ms: 110.0,
            sustain_level: 0.78,
            release_ms: 280.0,
            attack_curve: 0.55,
            decay_curve: 1.2,
            release_curve: 1.4,
            min_vibe: 0.06,
            max_vibe: 0.92,
            climax_enabled: false,
            climax_intensity: 0.7,
            climax_build_up_ms: 90_000.0,
            climax_tease_ratio: 0.18,
            climax_tease_drop: 0.35,
            climax_surge_boost: 0.5,
            climax_pulse_depth: 0.18,
            climax_pattern: ClimaxPattern::Wave,
        },
        Preset {
            name: "Domi Edge",
            description: "Domi 2 edging — tight bass pulses, low sustain, dramatic contrast",
            category: PresetCategory::Percussion,
            main_volume: 2.10,
            frequency_mode: FrequencyMode::LowPass,
            target_frequency: 120.0,
            gate_threshold: 0.20,
            auto_gate_amount: 0.0,
            gate_smoothing: 0.0,
            trigger_mode: TriggerMode::Hybrid,
            binary_level: 0.92,
            hybrid_blend: 0.55,
            attack_ms: 1.0,
            decay_ms: 35.0,
            sustain_level: 0.28,
            release_ms: 180.0,
            attack_curve: 0.25,
            decay_curve: 2.2,
            release_curve: 1.8,
            min_vibe: 0.0,
            max_vibe: 1.0,
            climax_enabled: false,
            climax_intensity: 0.7,
            climax_build_up_ms: 90_000.0,
            climax_tease_ratio: 0.18,
            climax_tease_drop: 0.35,
            climax_surge_boost: 0.5,
            climax_pulse_depth: 0.18,
            climax_pattern: ClimaxPattern::Wave,
        },
        // === NEW PRESETS ===
        Preset {
            name: "Deep Trance",
            description: "Hypnotic bass pulse — slow, deep, relentless build",
            category: PresetCategory::Bass,
            main_volume: 1.8,
            frequency_mode: FrequencyMode::LowPass,
            target_frequency: 100.0,
            gate_threshold: 0.10,
            auto_gate_amount: 0.0,
            gate_smoothing: 0.15,
            trigger_mode: TriggerMode::Dynamic,
            binary_level: 0.8,
            hybrid_blend: 0.5,
            attack_ms: 15.0,
            decay_ms: 200.0,
            sustain_level: 0.82,
            release_ms: 600.0,
            attack_curve: 0.5,
            decay_curve: 0.8,
            release_curve: 1.2,
            min_vibe: 0.12,
            max_vibe: 1.0,
            climax_enabled: false,
            climax_intensity: 0.7,
            climax_build_up_ms: 90_000.0,
            climax_tease_ratio: 0.18,
            climax_tease_drop: 0.35,
            climax_surge_boost: 0.5,
            climax_pulse_depth: 0.18,
            climax_pattern: ClimaxPattern::Wave,
        },
        Preset {
            name: "Edge & Deny",
            description: "Builds intensity then deliberately pulls back — designed to delay and intensify",
            category: PresetCategory::Effect,
            main_volume: 1.6,
            frequency_mode: FrequencyMode::Full,
            target_frequency: 200.0,
            gate_threshold: 0.08,
            auto_gate_amount: 0.0,
            gate_smoothing: 0.10,
            trigger_mode: TriggerMode::Dynamic,
            binary_level: 0.8,
            hybrid_blend: 0.5,
            attack_ms: 20.0,
            decay_ms: 100.0,
            sustain_level: 0.85,
            release_ms: 350.0,
            attack_curve: 0.6,
            decay_curve: 1.0,
            release_curve: 1.3,
            min_vibe: 0.08,
            max_vibe: 0.95,
            climax_enabled: false,
            climax_intensity: 0.7,
            climax_build_up_ms: 90_000.0,
            climax_tease_ratio: 0.18,
            climax_tease_drop: 0.35,
            climax_surge_boost: 0.5,
            climax_pulse_depth: 0.18,
            climax_pattern: ClimaxPattern::Wave,
        },
        Preset {
            name: "Slow Burn",
            description: "Ultra-gradual build — barely perceptible increase over minutes, then overwhelming",
            category: PresetCategory::Effect,
            main_volume: 1.2,
            frequency_mode: FrequencyMode::Full,
            target_frequency: 200.0,
            gate_threshold: 0.06,
            auto_gate_amount: 0.0,
            gate_smoothing: 0.25,
            trigger_mode: TriggerMode::Dynamic,
            binary_level: 0.8,
            hybrid_blend: 0.5,
            attack_ms: 50.0,
            decay_ms: 300.0,
            sustain_level: 0.90,
            release_ms: 800.0,
            attack_curve: 0.4,
            decay_curve: 0.7,
            release_curve: 1.0,
            min_vibe: 0.05,
            max_vibe: 0.80,
            climax_enabled: false,
            climax_intensity: 0.7,
            climax_build_up_ms: 90_000.0,
            climax_tease_ratio: 0.18,
            climax_tease_drop: 0.35,
            climax_surge_boost: 0.5,
            climax_pulse_depth: 0.18,
            climax_pattern: ClimaxPattern::Wave,
        },
        Preset {
            name: "Rhythm Rider",
            description: "Locks to any beat — punchy dynamic response with musical sustain tail",
            category: PresetCategory::Percussion,
            main_volume: 1.4,
            frequency_mode: FrequencyMode::Full,
            target_frequency: 200.0,
            gate_threshold: 0.15,
            auto_gate_amount: 0.2,
            gate_smoothing: 0.05,
            trigger_mode: TriggerMode::Hybrid,
            binary_level: 0.75,
            hybrid_blend: 0.35,
            attack_ms: 3.0,
            decay_ms: 80.0,
            sustain_level: 0.55,
            release_ms: 180.0,
            attack_curve: 0.3,
            decay_curve: 1.5,
            release_curve: 2.0,
            min_vibe: 0.0,
            max_vibe: 1.0,
            climax_enabled: false,
            climax_intensity: 0.7,
            climax_build_up_ms: 90_000.0,
            climax_tease_ratio: 0.18,
            climax_tease_drop: 0.35,
            climax_surge_boost: 0.5,
            climax_pulse_depth: 0.18,
            climax_pattern: ClimaxPattern::Wave,
        },
        Preset {
            name: "Crescendo",
            description: "Designed for the climax engine — builds relentlessly with musical dynamics",
            category: PresetCategory::Musical,
            main_volume: 1.3,
            frequency_mode: FrequencyMode::Full,
            target_frequency: 200.0,
            gate_threshold: 0.07,
            auto_gate_amount: 0.0,
            gate_smoothing: 0.18,
            trigger_mode: TriggerMode::Dynamic,
            binary_level: 0.8,
            hybrid_blend: 0.5,
            attack_ms: 25.0,
            decay_ms: 150.0,
            sustain_level: 0.88,
            release_ms: 450.0,
            attack_curve: 0.5,
            decay_curve: 0.9,
            release_curve: 1.2,
            min_vibe: 0.10,
            max_vibe: 0.95,
            climax_enabled: false,
            climax_intensity: 0.7,
            climax_build_up_ms: 90_000.0,
            climax_tease_ratio: 0.18,
            climax_tease_drop: 0.35,
            climax_surge_boost: 0.5,
            climax_pulse_depth: 0.18,
            climax_pattern: ClimaxPattern::Wave,
        },
        // === NEW INTENSITY PRESETS ===
        Preset {
            name: "Overwhelm",
            description: "Full-spectrum maximum — every band drives output, relentless sustained intensity with chaos modulation",
            category: PresetCategory::Effect,
            main_volume: 2.5,
            frequency_mode: FrequencyMode::Full,
            target_frequency: 200.0,
            gate_threshold: 0.04,
            auto_gate_amount: 0.0,
            gate_smoothing: 0.08,
            trigger_mode: TriggerMode::Hybrid,
            binary_level: 0.95,
            hybrid_blend: 0.40,
            attack_ms: 5.0,
            decay_ms: 40.0,
            sustain_level: 0.95,
            release_ms: 150.0,
            attack_curve: 0.25,
            decay_curve: 0.8,
            release_curve: 1.1,
            min_vibe: 0.15,
            max_vibe: 1.0,
            climax_enabled: false,
            climax_intensity: 0.7,
            climax_build_up_ms: 90_000.0,
            climax_tease_ratio: 0.18,
            climax_tease_drop: 0.35,
            climax_surge_boost: 0.5,
            climax_pulse_depth: 0.18,
            climax_pattern: ClimaxPattern::Wave,
        },
        Preset {
            name: "Bass Destroyer",
            description: "Sub-bass locks both motors to the kick — thundering dual-motor pulses that hit from the inside",
            category: PresetCategory::Bass,
            main_volume: 2.8,
            frequency_mode: FrequencyMode::LowPass,
            target_frequency: 90.0,
            gate_threshold: 0.10,
            auto_gate_amount: 0.0,
            gate_smoothing: 0.04,
            trigger_mode: TriggerMode::Hybrid,
            binary_level: 1.0,
            hybrid_blend: 0.55,
            attack_ms: 1.0,
            decay_ms: 45.0,
            sustain_level: 0.70,
            release_ms: 100.0,
            attack_curve: 0.2,
            decay_curve: 1.8,
            release_curve: 2.2,
            min_vibe: 0.08,
            max_vibe: 1.0,
            climax_enabled: false,
            climax_intensity: 0.7,
            climax_build_up_ms: 90_000.0,
            climax_tease_ratio: 0.18,
            climax_tease_drop: 0.35,
            climax_surge_boost: 0.5,
            climax_pulse_depth: 0.18,
            climax_pattern: ClimaxPattern::Wave,
        },
        Preset {
            name: "Psy Spiral",
            description: "Trance-optimized — 126-128 BPM hypnotic build with sub-harmonic resonance and edge-deny cycles",
            category: PresetCategory::Effect,
            main_volume: 2.0,
            frequency_mode: FrequencyMode::LowPass,
            target_frequency: 120.0,
            gate_threshold: 0.08,
            auto_gate_amount: 0.0,
            gate_smoothing: 0.12,
            trigger_mode: TriggerMode::Dynamic,
            binary_level: 0.8,
            hybrid_blend: 0.5,
            attack_ms: 10.0,
            decay_ms: 180.0,
            sustain_level: 0.88,
            release_ms: 500.0,
            attack_curve: 0.45,
            decay_curve: 0.85,
            release_curve: 1.15,
            min_vibe: 0.12,
            max_vibe: 1.0,
            climax_enabled: false,
            climax_intensity: 0.7,
            climax_build_up_ms: 90_000.0,
            climax_tease_ratio: 0.18,
            climax_tease_drop: 0.35,
            climax_surge_boost: 0.5,
            climax_pulse_depth: 0.18,
            climax_pattern: ClimaxPattern::Wave,
        },
        Preset {
            name: "Nerve Storm",
            description: "Maximum chaos — unpredictable aperiodic modulation with aggressive onset response, impossible to anticipate",
            category: PresetCategory::Effect,
            main_volume: 2.2,
            frequency_mode: FrequencyMode::Full,
            target_frequency: 200.0,
            gate_threshold: 0.05,
            auto_gate_amount: 0.15,
            gate_smoothing: 0.03,
            trigger_mode: TriggerMode::Dynamic,
            binary_level: 0.9,
            hybrid_blend: 0.5,
            attack_ms: 2.0,
            decay_ms: 30.0,
            sustain_level: 0.82,
            release_ms: 80.0,
            attack_curve: 0.2,
            decay_curve: 1.4,
            release_curve: 1.8,
            min_vibe: 0.05,
            max_vibe: 1.0,
            climax_enabled: false,
            climax_intensity: 0.7,
            climax_build_up_ms: 90_000.0,
            climax_tease_ratio: 0.18,
            climax_tease_drop: 0.35,
            climax_surge_boost: 0.5,
            climax_pulse_depth: 0.18,
            climax_pattern: ClimaxPattern::Wave,
        },
        Preset {
            name: "Domi Annihilate",
            description: "Domi 2 dual-motor maximum — both motors independently driven with phase offset, full sub-bass lock",
            category: PresetCategory::Bass,
            main_volume: 2.6,
            frequency_mode: FrequencyMode::LowPass,
            target_frequency: 100.0,
            gate_threshold: 0.06,
            auto_gate_amount: 0.0,
            gate_smoothing: 0.06,
            trigger_mode: TriggerMode::Hybrid,
            binary_level: 0.95,
            hybrid_blend: 0.50,
            attack_ms: 3.0,
            decay_ms: 50.0,
            sustain_level: 0.90,
            release_ms: 120.0,
            attack_curve: 0.3,
            decay_curve: 1.2,
            release_curve: 1.5,
            min_vibe: 0.10,
            max_vibe: 1.0,
            climax_enabled: false,
            climax_intensity: 0.7,
            climax_build_up_ms: 90_000.0,
            climax_tease_ratio: 0.18,
            climax_tease_drop: 0.35,
            climax_surge_boost: 0.5,
            climax_pulse_depth: 0.18,
            climax_pattern: ClimaxPattern::Wave,
        },
        // === EXPERIENCE PRESETS (climax engine enabled) ===
        Preset {
            name: "Slow Tease",
            description: "Long edging cycle — deep denial drops, gentle rebuilds, designed to keep you right on the edge",
            category: PresetCategory::Effect,
            main_volume: 1.5,
            frequency_mode: FrequencyMode::Full,
            target_frequency: 200.0,
            gate_threshold: 0.07,
            auto_gate_amount: 0.0,
            gate_smoothing: 0.18,
            trigger_mode: TriggerMode::Dynamic,
            binary_level: 0.8,
            hybrid_blend: 0.5,
            attack_ms: 25.0,
            decay_ms: 140.0,
            sustain_level: 0.88,
            release_ms: 400.0,
            attack_curve: 0.5,
            decay_curve: 0.9,
            release_curve: 1.2,
            min_vibe: 0.08,
            max_vibe: 0.92,
            climax_enabled: true,
            climax_intensity: 0.8,
            climax_build_up_ms: 120_000.0,
            climax_tease_ratio: 0.30,
            climax_tease_drop: 0.70,
            climax_surge_boost: 0.6,
            climax_pulse_depth: 0.12,
            climax_pattern: ClimaxPattern::Wave,
        },
        Preset {
            name: "Ride the Beat",
            description: "Music-locked escalation — chaos + sub-harmonic resonance sync to the rhythm, builds across cycles",
            category: PresetCategory::Musical,
            main_volume: 1.7,
            frequency_mode: FrequencyMode::Full,
            target_frequency: 200.0,
            gate_threshold: 0.10,
            auto_gate_amount: 0.15,
            gate_smoothing: 0.08,
            trigger_mode: TriggerMode::Hybrid,
            binary_level: 0.80,
            hybrid_blend: 0.35,
            attack_ms: 5.0,
            decay_ms: 80.0,
            sustain_level: 0.72,
            release_ms: 200.0,
            attack_curve: 0.35,
            decay_curve: 1.3,
            release_curve: 1.6,
            min_vibe: 0.05,
            max_vibe: 1.0,
            climax_enabled: true,
            climax_intensity: 0.7,
            climax_build_up_ms: 60_000.0,
            climax_tease_ratio: 0.15,
            climax_tease_drop: 0.35,
            climax_surge_boost: 0.7,
            climax_pulse_depth: 0.22,
            climax_pattern: ClimaxPattern::Surge,
        },
        Preset {
            name: "Break Me",
            description: "No restraint — extreme surge, aggressive deny cycles, dual motor anti-phase, maximum chaos",
            category: PresetCategory::Effect,
            main_volume: 2.4,
            frequency_mode: FrequencyMode::Full,
            target_frequency: 200.0,
            gate_threshold: 0.05,
            auto_gate_amount: 0.0,
            gate_smoothing: 0.05,
            trigger_mode: TriggerMode::Hybrid,
            binary_level: 0.95,
            hybrid_blend: 0.45,
            attack_ms: 2.0,
            decay_ms: 35.0,
            sustain_level: 0.92,
            release_ms: 100.0,
            attack_curve: 0.25,
            decay_curve: 1.1,
            release_curve: 1.4,
            min_vibe: 0.12,
            max_vibe: 1.0,
            climax_enabled: true,
            climax_intensity: 1.0,
            climax_build_up_ms: 45_000.0,
            climax_tease_ratio: 0.22,
            climax_tease_drop: 0.55,
            climax_surge_boost: 1.2,
            climax_pulse_depth: 0.35,
            climax_pattern: ClimaxPattern::Surge,
        },
    ]
}

/// Lazily-initialized static preset list (avoids per-frame allocation)
fn cached_presets() -> &'static [Preset] {
    use std::sync::OnceLock;
    static PRESETS: OnceLock<Vec<Preset>> = OnceLock::new();
    PRESETS.get_or_init(factory_presets)
}

/// Get a preset by name (case-insensitive)
pub fn find_preset(name: &str) -> Option<Preset> {
    cached_presets()
        .iter()
        .find(|p| p.name.eq_ignore_ascii_case(name))
        .cloned()
}

/// Get all presets in a given category
pub fn presets_in_category(category: PresetCategory) -> Vec<Preset> {
    cached_presets()
        .iter()
        .filter(|p| p.category == category)
        .cloned()
        .collect()
}
